'use client'

import React, { createContext, useContext, useEffect, useState } from 'react'

export type Language = 'th' | 'en'

export const translations = {
  th: {
    // Brand & Common
    appName: 'QFlow',
    appTagline: 'ระบบจองคิวบริการ & ตรวจสลิปมัดจำอัตโนมัติ',
    save: 'บันทึก',
    cancel: 'ยกเลิก',
    close: 'ปิด',
    copy: 'คัดลอก',
    copied: 'คัดลอกแล้ว',
    back: 'ย้อนกลับ',
    next: 'ต่อไป',
    confirm: 'ยืนยัน',
    delete: 'ลบ',
    edit: 'แก้ไข',
    status: 'สถานะ',
    today: 'วันนี้',
    tomorrow: 'พรุ่งนี้',
    all: 'ทั้งหมด',
    loading: 'กำลังโหลด...',
    errorOccurred: 'เกิดข้อผิดพลาด',
    free: 'ฟรี',
    baht: 'บาท',
    minutes: 'นาที',
    live: 'เปิดใช้งาน',

    // Landing Page
    heroTitle1: 'ระบบจองคิวบริการ',
    heroTitle2: 'ตรวจสลิปมัดจำอัตโนมัติ 3 คลิก',
    heroDesc: 'หมดปัญหาลูกค้า No-Show, ตอบแชทช้า, หรือเช็กสลิปปลอมมือหมุน ด้วยระบบจองคิวผ่าน LINE LIFF & Responsive Web สำหรับธุรกิจ SME ขนาดเล็ก',
    start: 'เริ่มใช้งาน',
    testBookingUI: 'ทดสอบ Client Booking UI',
    viewDemo: 'ดูตัวอย่างหน้าจอง (Demo)',
    openShopNow: 'เปิดร้านตอนนี้',
    demoShopTitle: 'ตัวอย่างร้านค้าทดสอบ (Demo Shop)',
    demoShopSubtitle: 'ทดลองสัมผัส Flow การจองจริง หรือเข้าดูหน้าจัดการตารางคิว',
    demoShopBook: 'ร้านตัวอย่าง (หน้าจองคิวลูกค้า)',
    demoShopDashboard: 'ร้านตัวอย่าง (Dashboard หลังบ้าน)',
    uvp1Title: 'Smart Queue, Seamless Flow',
    uvp1Desc: 'ลูกค้าเลือกรอบวัน/เวลา/บริการ จบใน 3 คลิกผ่าน LINE LIFF ดึงชื่อโปรไฟล์อัตโนมัติ จองได้ตลอด 24 ชม.',
    uvp2Title: 'Auto-Slip & Deposit Check',
    uvp2Desc: 'สร้าง PromptPay QR ฝังยอดมัดจำ พร้อมต่อ SlipOK API ตรวจสลิป ป้องกันสลิปซ้ำ และเงินเข้าบัญชีร้าน 100%',
    uvp3Title: 'Merchant Dashboard',
    uvp3Desc: 'ดูตารางคิวประจำวัน บล็อกช่วงเวลาด่วน ตั้งเวลาพักเที่ยง และรับการแจ้งเตือนเมื่อมีลูกค้าจองสำเร็จทันที',

    // Onboarding
    onboardingBadge: 'Zero Friction Onboarding',
    onboardingTitle: 'เปิดระบบจองคิวร้านคุณ',
    onboardingSubtitle: 'กรอกเพียง 4 ข้อ รับลิงก์จองคิวพร้อมระบบตรวจสลิปมัดจำอัตโนมัติทันที',
    shopNameLabel: 'ชื่อร้านค้า / บริการ',
    shopNamePlaceholder: 'เช่น Barber & Salon, ช่างตัดผมพี่เอก',
    promptpayLabel: 'เบอร์โทร หรือ เลขบัตร/พร้อมเพย์รับเงิน',
    promptpayPlaceholder: 'เช่น 0812345678 หรือ 1409900000000',
    promptpayHint: 'ระบบจะใช้เลขนี้สร้าง QR Code พร้อมเพย์ให้ลูกค้าสแกนโอนตรงเข้าบัญชีคุณ',
    depositLabel: 'ยอดเงินมัดจำต่อคิว (บาท)',
    depositPlaceholder: 'เช่น 100, 200, 300',
    depositHint: 'กันปัญหา No-Show ลูกค้าจองแล้วไม่มา',
    customSlugLabel: 'URL ร้านค้า (กำหนดเองได้ หรือปล่อยว่างเพื่อให้ระบบสร้างให้อัตโนมัติ)',
    createShopBtn: 'เริ่มเปิดรับคิวทันที',
    creatingShop: 'กำลังสร้างระบบ...',
    onboardingSuccessTitle: 'สร้างร้านสำเร็จแล้ว! 🎉',
    onboardingSuccessDesc: 'พร้อมรับคิว 24 ชั่วโมง',
    yourBookingLink: 'Booking Link ของคุณ (นำไปวางใน LINE Rich Menu / เพจ)',
    testBookingBtn: 'ทดลองหน้าจอง',
    gotoDashboardBtn: 'จัดการหลังบ้าน',

    // Booking Page
    stepOf: 'ขั้นตอนที่ {step} จาก 3',
    step1Title: '1. เลือกบริการที่ต้องการ',
    step1Subtitle: 'แตะเพื่อเลือกบริการที่ต้องการจอง',
    step2Title: '2. เลือกวันและรอบเวลา',
    step2Subtitle: 'เลือกวันที่และรอบเวลาที่สะดวกเข้าใช้บริการ',
    step3Title: '3. กรอกข้อมูลเพื่อยืนยันคิว',
    step3Subtitle: 'ตรวจสอบสรุปรายการและกรอกข้อมูลติดต่อ',
    selectedService: 'บริการที่เลือก',
    change: 'เปลี่ยน',
    selectDate: 'เลือกวันที่',
    selectTimeSlot: 'เลือกรอบเวลาว่าง',
    depositAmount: 'มัดจำ',
    fullPrice: 'ราคาเต็ม',
    calculatingSlots: 'กำลังคำนวณคิวว่าง...',
    noAvailableSlots: 'ไม่มีรอบเวลาว่างในวันที่เลือก',
    nextCustomerInfo: 'ต่อไป: กรอกข้อมูลผู้จอง',
    bookingSummary: 'สรุปรายการจอง',
    service: 'บริการ',
    dateTime: 'วัน/เวลา',
    depositToPay: 'ยอดเงินมัดจำที่ต้องชำระ',
    customerName: 'ชื่อ-นามสกุล / ชื่อเล่น',
    customerNamePlaceholder: 'เช่น คุณสมศรี, น้องแพรว',
    customerPhone: 'เบอร์โทรศัพท์ติดต่อ',
    customerPhonePlaceholder: '08xxxxxxxx',
    customerLineId: 'LINE ID (เพื่อรับการแจ้งเตือนและการติดต่อจากทางร้าน)',
    customerLineIdPlaceholder: '@line_id หรือ ไอดีไลน์',
    customerNotes: 'หมายเหตุเพิ่มเติม / คำขอพิเศษ',
    customerNotesPlaceholder: 'เช่น แพ้น้ำยา, ต้องการช่างประจำ, อื่นๆ',
    confirmAndPayBtn: 'ยืนยันการจอง & ไปหน้าชำระมัดจำ',
    submittingBooking: 'กำลังดำเนินการ...',
    shopBreakTime: 'เวลาพักของร้าน (Break)',
    slotBooked: 'มีลูกค้าจองแล้ว',
    slotBlocked: 'ร้านปิดรับรอบนี้',
    slotPast: 'หมดเวลาจอง',

    // Payment & Confirmation
    pendingPayment: 'รอชำระเงินมัดจำ',
    confirmedBooking: 'ยืนยันคิวแล้ว',
    scanPromptPay: 'สแกนจ่ายผ่าน PromptPay QR',
    depositPrice: 'ยอดเงินมัดจำ',
    promptpayNumber: 'เลขพร้อมเพย์',
    saveQrImage: 'บันทึกรูป QR Code ลงมือถือ',
    attachSlipTitle: 'แนบสลิปการโอนเงินเพื่อยืนยันคิว',
    attachSlipSubtitle: 'ระบบจะตรวจสลิปผ่าน SlipOK ทันที เมื่อถูกต้องจะล็อกคิวให้อัตโนมัติ',
    chooseSlipImage: 'แตะเพื่อเลือกรูปภาพสลิป',
    changeSlipImage: 'แตะเพื่อเปลี่ยนรูปสลิป',
    supportedFiles: 'รองรับไฟล์ JPG, PNG จากแอปธนาคาร',
    verifySlipBtn: 'ตรวจสอบสลิป & ยืนยันการจอง',
    verifyingSlip: 'กำลังตรวจสอบสลิปผ่าน SlipOK...',
    bookingSuccessTitle: 'จองคิวสำเร็จแล้ว! 🎉',
    bookingSuccessSubtitle: 'ระบบได้ตรวจสลิปและล็อกคิวของคุณเรียบร้อยแล้ว',
    bookingId: 'รหัสคิว (Booking ID)',
    bookMoreBtn: 'จองคิวใหม่ / จองเพิ่ม',
    payWithin10Min: 'กรุณาชำระเงินและแนบสลิปภายใน 10 นาที',
    countdownRemaining: 'เหลือเวลาทำรายการ',
    expiredWarning: 'หากไม่แนบสลิปภายในเวลา ระบบจะยกเลิกคิวเพื่อเปิดให้ผู้อื่นจอง',
    bookingExpiredTitle: 'หมดเวลาการชำระเงินมัดจำ (หลุดจอง)',
    bookingExpiredDesc: 'รายการจองนี้ถูกยกเลิกแล้ว เนื่องจากไม่ได้รับการแนบสลิปภายในเวลา 10 นาที เพื่อเปิดโอกาสให้ผู้อื่นสามารถจองรอบเวลานี้ได้',
    bookAgainBtn: 'เลือกจองคิวใหม่',

    // Dashboard
    dashboardTitle: 'Merchant Admin Center',
    openCustomerBooking: 'เปิดหน้าจองลูกค้า',
    todayBookings: 'คิวทั้งหมดวันนี้',
    todayConfirmed: 'ยืนยันมัดจำแล้ว',
    todayDepositTotal: 'ยอดมัดจำวันนี้',
    shopHours: 'เวลาร้านเปิด',
    shopBreakTimeLabel: 'เวลาพักร้าน',
    tabBookings: 'ตารางคิวงาน',
    addManualBookingBtn: 'ลงคิวเอง',
    manualBookingTitle: 'ลงคิวจองด้วยตนเอง',
    tabBlockSlots: 'บล็อกเวลาด่วน',
    tabServices: 'จัดการสาขาและบริการ',
    tabBranchesAndServices: 'จัดการสาขาและบริการ',
    tabSettings: 'ตั้งค่าร้าน',
    noBookingsFound: 'ไม่มีรายการจองในวันที่เลือก',
    customer: 'ลูกค้า',
    phone: 'เบอร์โทร',
    lineId: 'LINE ID',
    notes: 'หมายเหตุ',
    viewSlip: 'ดูรูปสลิป',
    markCompleted: 'เข้าบริการเสร็จสิ้น',
    cancelBooking: 'ยกเลิกคิว',
    statusConfirmed: 'ยืนยันสลิปแล้ว',
    statusCompleted: 'เข้าใช้บริการแล้ว',
    statusCancelled: 'ยกเลิกคิว',
    statusPending: 'รอตรวจสลิป',
    statusNoShow: 'ไม่มาตามนัด',
    selectService: 'เลือกบริการ',
    bookingDate: 'วันที่จอง',
    bookingStartTime: 'เวลาเริ่มบริการ',
    bookingStatusLabel: 'สถานะการจอง & การชำระเงิน',
    statusConfirmedPay: 'ยืนยันแล้ว (โอนมัดจำแล้ว / ชำระแล้ว)',
    statusPendingPay: 'รอชำระเงินหน้าร้าน',
    createBookingBtn: 'บันทึกลงคิวงาน',
    bookingCreatedSuccess: 'ลงคิวงานเรียบร้อยแล้ว',

    // Block Slots Tab
    blockSlotTitle: 'บล็อกช่วงเวลาด่วน (ไม่ให้ลูกค้าจอง)',
    date: 'วันที่',
    startTime: 'เวลาเริ่ม',
    endTime: 'เวลาสิ้นสุด',
    reason: 'เหตุผล',
    reasonPlaceholder: 'เช่น พักเที่ยง, ลากิจ',
    saveBlockBtn: 'บันทึกการบล็อกเวลา',
    blockedListTitle: 'รายการเวลาที่ถูกบล็อก',
    noBlockedSlots: 'ไม่มีช่วงเวลาที่ถูกบล็อก',

    // Services & Branches & Staff Tab
    branchInfoTitle: 'ข้อมูลสาขาและที่ตั้ง',
    branchName: 'ชื่อสาขา',
    branchAddress: 'ที่อยู่ / พิกัดสาขา',
    branchPhone: 'เบอร์โทรประจำสาขา',
    allBranchesTitle: 'รายชื่อสาขาทั้งหมด',
    addNewBranchBtn: 'เพิ่มสาขาใหม่',
    editBranchTitle: 'แก้ไขข้อมูลสาขา',
    noBranchesYet: 'ยังไม่มีสาขาเพิ่มเติม (ใช้สาขาหลัก)',
    allStaffTitle: 'ช่าง / ผู้ให้บริการประจำสาขา',
    addNewStaffBtn: 'เพิ่มช่าง / ผู้ให้บริการ',
    editStaffTitle: 'แก้ไขข้อมูลช่าง',
    staffName: 'ชื่อช่าง / ผู้ให้บริการ',
    staffNickname: 'ชื่อเล่น',
    staffRoleTitle: 'ตำแหน่ง / ความเชี่ยวชาญ',
    staffBranch: 'สาขาที่ประจำ',
    staffServices: 'บริการที่ช่างท่านนี้ให้บริการได้',
    noStaffYet: 'ยังไม่ได้เพิ่มรายชื่อช่าง (คิวจะนับรวมทั้งร้าน)',
    selectBranch: 'เลือกสาขา',
    selectStaff: 'เลือกช่าง / ผู้ให้บริการ',
    anyStaff: 'ช่างท่านใดก็ได้ (เร็วที่สุด)',
    allServicesTitle: 'รายการบริการทั้งหมด',
    addNewServiceBtn: 'เพิ่มบริการใหม่',
    editServiceTitle: 'แก้ไขบริการ',
    serviceName: 'ชื่อบริการ',
    serviceDesc: 'รายละเอียดบริการ',
    durationMin: 'ระยะเวลา (นาที)',
    servicePrice: 'ราคาเต็ม (บาท)',
    serviceDeposit: 'ยอดเงินมัดจำ (เว้นว่างเพื่อใช้ค่าเริ่มต้นของร้าน)',

    // Settings Tab
    shopSettingsTitle: 'ตั้งค่าร้านค้า & สาขา',
    shopLogoLabel: 'รูปโปรไฟล์ / โลโก้ร้านค้า',
    uploadLogoBtn: 'เปลี่ยนรูปโปรไฟล์',
    uploadingLogo: 'กำลังอัปโหลด...',
    shopName: 'ชื่อร้าน',
    shopPhone: 'เบอร์ติดต่อร้าน',
    promptpayAccountName: 'ชื่อบัญชีพร้อมเพย์',
    openTime: 'เวลาเปิดร้าน',
    closeTime: 'เวลาปิดร้าน',
    closedDaysTitle: 'วันหยุดประจำสัปดาห์ (วันปิดทำการ)',
    closedDaysDesc: 'ลูกค้าจะไม่สามารถเลือกจองคิวในวันที่ร้านปิดประจำสัปดาห์ได้โดยอัตโนมัติ',
    enableDailyBreak: 'เปิดใช้งานเวลาพักประจำวัน (เช่น พักเที่ยง)',
    breakStartTime: 'เวลาเริ่มพัก',
    breakEndTime: 'เวลาสิ้นสุดพัก',
    defaultDepositAmount: 'ค่ามัดจำเริ่มต้น (บาท)',
    slotInterval: 'ช่วงความถี่รอบจอง',
    every15Min: 'ทุก 15 นาที',
    every30Min: 'ทุก 30 นาที',
    every60Min: 'ทุก 60 นาที',
    lineNotifyTokenLabel: 'LINE Notify Token (แจ้งเตือนเข้ากลุ่มแอดมินเมื่อมีคิวใหม่)',
    saveSettingsBtn: 'บันทึกการตั้งค่าร้านค้า',
    settingsSaved: 'บันทึกการตั้งค่าเรียบร้อยแล้ว',
  },
  en: {
    // Brand & Common
    appName: 'QFlow',
    appTagline: 'Smart Booking & Auto-Deposit Verification',
    save: 'Save',
    cancel: 'Cancel',
    close: 'Close',
    copy: 'Copy',
    copied: 'Copied',
    back: 'Back',
    next: 'Next',
    confirm: 'Confirm',
    delete: 'Delete',
    edit: 'Edit',
    status: 'Status',
    today: 'Today',
    tomorrow: 'Tomorrow',
    all: 'All',
    loading: 'Loading...',
    errorOccurred: 'An error occurred',
    free: 'Free',
    baht: 'THB',
    minutes: 'mins',
    live: 'Live',

    // Landing Page
    heroTitle1: 'Service Booking Engine',
    heroTitle2: 'Auto-Deposit Verification in 3 Clicks',
    heroDesc: 'Eliminate no-shows, slow chat replies, and fake slips with automated LINE LIFF & Web booking for SME businesses.',
    start: 'Get Started Free',
    testBookingUI: 'Test Booking UI',
    viewDemo: 'View Booking Demo',
    openShopNow: 'Open Shop Now',
    demoShopTitle: 'Interactive Demo Shop',
    demoShopSubtitle: 'Experience the real customer flow or access the merchant dashboard.',
    demoShopBook: 'Demo Shop (Customer Booking Flow)',
    demoShopDashboard: 'Demo Shop (Merchant Dashboard)',
    uvp1Title: 'Smart Queue, Seamless Flow',
    uvp1Desc: 'Customers pick slots in 3 clicks via LINE LIFF with auto-profile fill 24/7.',
    uvp2Title: 'Auto-Slip & Deposit Check',
    uvp2Desc: 'Dynamic PromptPay QR SlipOK API prevents duplicate slips and secures your deposit directly.',
    uvp3Title: 'Merchant Dashboard',
    uvp3Desc: 'Manage daily appointments, quick-block emergency slots, set lunch breaks, and receive instant alerts.',

    // Onboarding
    onboardingBadge: '60-Second Zero Friction Onboarding',
    onboardingTitle: 'Launch Your Booking System',
    onboardingSubtitle: 'Fill 3 simple fields to get your instant booking link with auto-deposit verification.',
    shopNameLabel: 'Shop / Service Name',
    shopNamePlaceholder: 'e.g. Barber Studio, Elite Salon',
    promptpayLabel: 'PromptPay Phone or ID Number',
    promptpayPlaceholder: 'e.g. 0812345678 or 1409900000000',
    promptpayHint: 'Used to generate QR Codes for direct instant customer bank transfers.',
    depositLabel: 'Deposit Amount per Booking (THB)',
    depositPlaceholder: 'e.g. 100, 200, 300',
    depositHint: 'Eliminates no-shows and secures booking slots.',
    customSlugLabel: 'Shop URL Slug (Optional)',
    createShopBtn: 'Launch Booking System',
    creatingShop: 'Creating System...',
    onboardingSuccessTitle: 'Shop Created Successfully! 🎉',
    onboardingSuccessDesc: 'Ready to accept bookings 24/7',
    yourBookingLink: 'Your Booking Link (Paste in LINE Rich Menu / Bio)',
    testBookingBtn: 'Try Booking Flow',
    gotoDashboardBtn: 'Open Merchant Dashboard',

    // Booking Page
    stepOf: 'Step {step} of 3',
    step1Title: '1. Select Service',
    step1Subtitle: 'Tap to choose your desired treatment or service',
    step2Title: '2. Select Date & Time',
    step2Subtitle: 'Choose your preferred date and available time slot',
    step3Title: '3. Fill Info & Confirm',
    step3Subtitle: 'Review your booking summary and provide contact details',
    selectedService: 'Selected Service',
    change: 'Change',
    selectDate: 'Select Date',
    selectTimeSlot: 'Select Available Time Slot',
    depositAmount: 'Deposit',
    fullPrice: 'Full Price',
    calculatingSlots: 'Calculating available slots...',
    noAvailableSlots: 'No available time slots on this date',
    nextCustomerInfo: 'Next: Customer Info',
    bookingSummary: 'Booking Summary',
    service: 'Service',
    dateTime: 'Date / Time',
    depositToPay: 'Deposit Due Now',
    customerName: 'Full Name / Nickname',
    customerNamePlaceholder: 'e.g. Jane Doe',
    customerPhone: 'Phone Number',
    customerPhonePlaceholder: '08xxxxxxxx',
    customerLineId: 'LINE ID (For booking alerts & updates)',
    customerLineIdPlaceholder: '@line_id or username',
    customerNotes: 'Special Notes / Requests',
    customerNotesPlaceholder: 'e.g. Allergies, preferred stylist, etc.',
    confirmAndPayBtn: 'Confirm & Proceed to Deposit',
    submittingBooking: 'Processing...',
    shopBreakTime: 'Shop Break Time',
    slotBooked: 'Booked by another customer',
    slotBlocked: 'Slot unavailable',
    slotPast: 'Slot time has passed',

    // Payment & Confirmation
    pendingPayment: 'Pending Deposit Payment',
    confirmedBooking: 'Booking Confirmed',
    scanPromptPay: 'Scan with Any Bank App via PromptPay QR',
    depositPrice: 'Deposit Amount',
    promptpayNumber: 'PromptPay Number',
    saveQrImage: 'Save QR Image to Device',
    attachSlipTitle: 'Attach Bank Transfer Slip to Confirm',
    attachSlipSubtitle: 'SlipOK will instantly verify the slip and lock your slot automatically.',
    chooseSlipImage: 'Tap to Select Transfer Slip',
    changeSlipImage: 'Tap to Change Slip Image',
    supportedFiles: 'Supports JPG, PNG from banking apps',
    verifySlipBtn: 'Verify Slip & Confirm Booking',
    verifyingSlip: 'Verifying slip with SlipOK...',
    bookingSuccessTitle: 'Booking Successful! 🎉',
    bookingSuccessSubtitle: 'Your slip has been verified and your appointment is locked.',
    bookingId: 'Booking ID',
    bookMoreBtn: 'Book Another Slot',
    payWithin10Min: 'Please pay deposit & attach slip within 10 mins',
    countdownRemaining: 'Time Remaining',
    expiredWarning: 'If slip is not attached in time, this slot will be released for others',
    bookingExpiredTitle: 'Deposit Payment Expired',
    bookingExpiredDesc: 'This reservation has been cancelled because no payment slip was uploaded within 10 minutes.',
    bookAgainBtn: 'Book Again',

    // Dashboard
    dashboardTitle: 'Merchant Admin Center',
    openCustomerBooking: 'Open Customer Booking',
    todayBookings: "Today's Bookings",
    todayConfirmed: 'Deposit Confirmed',
    todayDepositTotal: "Today's Deposit Total",
    shopHours: 'Opening Hours',
    shopBreakTimeLabel: 'Lunch/Daily Break',
    tabBookings: 'Appointments',
    addManualBookingBtn: 'Manual Booking (Phone / Walk-in)',
    manualBookingTitle: 'Create Manual Booking (Phone / Walk-in)',
    tabBlockSlots: 'Quick Block',
    tabServices: 'Branches & Services',
    tabBranchesAndServices: 'Branches & Services',
    tabSettings: 'Settings',
    noBookingsFound: 'No bookings on selected date',
    customer: 'Customer',
    phone: 'Phone',
    lineId: 'LINE ID',
    notes: 'Notes',
    viewSlip: 'View Slip',
    markCompleted: 'Mark Completed',
    cancelBooking: 'Cancel Booking',
    statusConfirmed: 'Confirmed',
    statusCompleted: 'Completed',
    statusCancelled: 'Cancelled',
    statusPending: 'Pending Slip',
    statusNoShow: 'No Show',
    selectService: 'Select Service',
    bookingDate: 'Booking Date',
    bookingStartTime: 'Start Time',
    bookingStatusLabel: 'Booking & Payment Status',
    statusConfirmedPay: 'Confirmed (Deposit Paid)',
    statusPendingPay: 'Pending Payment at Shop',
    createBookingBtn: 'Book Appointment',
    bookingCreatedSuccess: 'Appointment booked successfully',

    // Block Slots Tab
    blockSlotTitle: 'Quick Block Time Slot',
    date: 'Date',
    startTime: 'Start Time',
    endTime: 'End Time',
    reason: 'Reason',
    reasonPlaceholder: 'e.g. Lunch break, personal errand',
    saveBlockBtn: 'Save Blocked Slot',
    blockedListTitle: 'Blocked Time Ranges',
    noBlockedSlots: 'No blocked time ranges',

    // Services & Branches & Staff Tab
    branchInfoTitle: 'Branch Profile & Location',
    branchName: 'Branch Name',
    branchAddress: 'Branch Address / Location',
    branchPhone: 'Branch Phone',
    allBranchesTitle: 'All Branches',
    addNewBranchBtn: 'Add New Branch',
    editBranchTitle: 'Edit Branch',
    noBranchesYet: 'No additional branches created (using main branch)',
    allStaffTitle: 'Staff & Service Providers',
    addNewStaffBtn: 'Add Staff / Specialist',
    editStaffTitle: 'Edit Staff Profile',
    staffName: 'Staff Full Name',
    staffNickname: 'Nickname',
    staffRoleTitle: 'Specialty / Role Title',
    staffBranch: 'Assigned Branch',
    staffServices: 'Services Provided by this Specialist',
    noStaffYet: 'No staff profiles added yet (bookings count shop-wide)',
    selectBranch: 'Select Branch',
    selectStaff: 'Select Specialist / Staff',
    anyStaff: 'Any Available Specialist',
    allServicesTitle: 'All Services',
    addNewServiceBtn: 'Add New Service',
    editServiceTitle: 'Edit Service',
    serviceName: 'Service Name',
    serviceDesc: 'Description',
    durationMin: 'Duration (minutes)',
    servicePrice: 'Full Price (THB)',
    serviceDeposit: 'Deposit (Leave blank for shop default)',

    // Settings Tab
    shopSettingsTitle: 'Shop & Branches',
    shopLogoLabel: 'Shop Profile / Logo',
    uploadLogoBtn: 'Change Profile Picture',
    uploadingLogo: 'Uploading...',
    shopName: 'Shop Name',
    shopPhone: 'Contact Phone',
    promptpayAccountName: 'PromptPay Account Name',
    openTime: 'Open Time',
    closeTime: 'Close Time',
    closedDaysTitle: 'Weekly Closed Days',
    closedDaysDesc: 'Customers will automatically be unable to select or book on weekly closed days.',
    enableDailyBreak: 'Enable Daily Break (e.g. Lunch Break)',
    breakStartTime: 'Break Start Time',
    breakEndTime: 'Break End Time',
    defaultDepositAmount: 'Default Deposit (THB)',
    slotInterval: 'Slot Interval',
    every15Min: 'Every 15 mins',
    every30Min: 'Every 30 mins',
    every60Min: 'Every 60 mins',
    lineNotifyTokenLabel: 'LINE Notify Token (Sends alerts to admin group upon new booking)',
    saveSettingsBtn: 'Save Shop Settings',
    settingsSaved: 'Settings saved successfully',
  },
} as const

type TranslationKeys = keyof typeof translations.th

interface LanguageContextType {
  lang: Language
  setLang: (lang: Language) => void
  toggleLang: () => void
  t: (key: TranslationKeys, params?: Record<string, string | number>) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Language>('th')

  useEffect(() => {
    const saved = localStorage.getItem('qflow_lang') as Language | null
    if (saved === 'th' || saved === 'en') {
      setLangState(saved)
    }
  }, [])

  function setLang(l: Language) {
    setLangState(l)
    localStorage.setItem('qflow_lang', l)
  }

  function toggleLang() {
    setLang(lang === 'th' ? 'en' : 'th')
  }

  function t(key: TranslationKeys, params?: Record<string, string | number>): string {
    let str: string = translations[lang][key] || translations.th[key] || key
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        str = str.replace(new RegExp(`\\{${k}\\}`, 'g'), String(v))
      })
    }
    return str
  }

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
